# Copyright 2020 Hewlett Packard Enterprise Development LP

# Dockerfile for building HMS fake State Manager for testing.
# Author: mpkelly
# Date: 26-February 2020

# Base image contains everything needed for Go building, just build.
FROM dtr.dev.cray.com/baseos/golang:1.14-alpine3.12 AS builder

COPY Test/fake-rfep.go ${GOPATH}/src/fake-rfep/

RUN set -ex && go build -v -i -o /usr/local/bin/fake-rfep fake-rfep

### Final Stage ###

FROM dtr.dev.cray.com/baseos/alpine:3.12
LABEL maintainer="Cray, Inc."
STOPSIGNAL SIGTERM

ENV PORT=27999
ENV GOODACCT=2

# Copy the final binary.

COPY --from=builder /usr/local/bin/fake-rfep /usr/local/bin

# Run the fake State Mgr daemon

CMD ["sh", "-c", "fake-rfep"]
