version: '3.7'
#THIS environment sets up all of SCSD
#  All dependencies -> HSM (vault, hm-collector, kafka), RTS (redfish sims) are all setup and active.
#  The SCSD binary is active.
#  No ports are exposed to the local system.
#  This will be used for integration testing.
networks:
  scsd:

services:
  integration-tests:
    build:
      context: test/integration/
      dockerfile: Dockerfile
    environment:
      - SCSD=cray-scsd:25309
      - HSM=cray-smd:27779
      - X_S0_XNAME=x0c0s480b0
      - X_S0_HOST=${COMPOSE_PROJECT_NAME}_x0c0s480b0_1
      - X_S0_PORT=34800
      - X_S1_XNAME=x0c0s481b0
      - X_S1_HOST=${COMPOSE_PROJECT_NAME}_x0c0s481b0_1
      - X_S1_PORT=34801
      - X_S2_XNAME=x0c0s482b0
      - X_S2_HOST=${COMPOSE_PROJECT_NAME}_x0c0s482b0_1
      - X_S2_PORT=34802
      - X_S3_XNAME=x0c0s483b0
      - X_S3_HOST=${COMPOSE_PROJECT_NAME}_x0c0s483b0_1
      - X_S3_PORT=34803
      #TODO: s4?
      #TODO: s5?
      - X_S6_XNAME=x0c0s486b0
      - X_S6_HOST=${COMPOSE_PROJECT_NAME}_x0c0s486b0_1
      - X_S6_PORT=34806
      - X_S7_XNAME=x0c0s487b0
      - X_S7_HOST=${COMPOSE_PROJECT_NAME}_x0c0s487b0_1
      - X_S7_PORT=34807
    depends_on:
      - cray-scsd
      - cray-smd
      - x0c0s480b0
      - x0c0s481b0
      - x0c0s482b0
      - x0c0s483b0
      - x0c0s486b0
      - x0c0s487b0
    networks:
      - scsd

  # A collection of 8 fake Redfish endpoints

  # x_s0 (Mountain)
  x0c0s480b0:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s480b0n0
      - BMCPORT=:34800
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s1 (Mountain)
  x0c0s481b0:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s481b0n0
      - BMCPORT=:34801
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s2 (Mountain)
  x0c0s482b0:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s482b0n0
      - BMCPORT=:34802
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s3 (Mountain)
  x0c0s483b0:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s483b0n0
      - BMCPORT=:34803
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  #TODO: x_s4?
  #TODO: x_s5?

  # x_s6 (Mountain)
  x0c0s486b0:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s486b0n0
      - BMCPORT=:34806
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s7 (Mountain)
  x0c0s487b0:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s487b0n0
      - BMCPORT=:34807
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  cray-scsd:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SCSD_SMD_URL=http://cray-smd:27779/hsm/v2
      - SCSD_HTTP_LISTEN_PORT=25309
      - SCSD_LOCAL_MODE=true
      - SCSD_LOG_LEVEL=TRACE
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      #TODO: not sure if this is needed for fake Mountain Redfish endpoint credentials
      #- VAULT_ENABLE=0
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
    networks:
      - scsd
    ports:
      - "25309:25309"
    depends_on:
      - cray-smd
      - cray-hms-hmcollector
      - redfish-simulator
      - vault-kv-enabler

  cray-smd:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.48.0
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    networks:
      - scsd

  cray-smd-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.48.0
    environment:
      - SMD_DBHOST=hmsds-postgres
      - SMD_DBPORT=5432
    depends_on:
      - hmsds-postgres
    networks:
      - scsd
    command: /entrypoint.sh smd-init

  hmsds-postgres:
    hostname: hmsds-postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    networks:
      - scsd

  vault:
    hostname: vault
    image: artifactory.algol60.net/docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    networks:
      - scsd

  vault-kv-enabler:
    image: artifactory.algol60.net/csm-docker/stable/vault-kv-enabler:1.13.4
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault
    networks:
      - scsd

  cray-hms-hmcollector:
    image: artifactory.algol60.net/csm-docker/stable/hms-hmcollector:2.12.4
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./configs/kafka_brokers.json:/configs/kafka_brokers.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    depends_on:
      - kafka
    networks:
      - scsd

  kafka:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-kafka:6.1.1
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
    networks:
      - scsd

  zookeeper:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - scsd

  redfish-simulator:
    image: artifactory.algol60.net/csm-docker/stable/hms-redfish-translation-service:1.13.3
    environment:
      - SCHEMA_VERSION=2019.1
      - LOG_LEVEL=TRACE
      - PRIVILEGE_REGISTRY_VERSION=1.0.4
      - SCRIPT_DIR_PREFIX=/tmp/redfish
      - VAULT_TOKEN=hms
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - VAULT_ADDR=http://vault:8200
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - HTTPS_CERT=configs/rts.crt
      - HTTPS_KEY=configs/rts.key
      - BACKEND_HELPER=RFSimulator
      - PERIODIC_SLEEP=120
      - COLLECTOR_URL=http://cray-hms-hmcollector
      - HSM_URL=http://cray-smd:27779
      - HMS_VAULT_KEYPATH=hms-creds
      - RF_USERNAME=root
      - RF_PASSWORD=testpassword
      - RF_SIMULATOR_XNAMES=x0c0s1b0,x0c0s2b0
    depends_on:
      - redis
      - vault
      - cray-smd
    networks:
      scsd:
        aliases:
          - x0c0s1b0
          - x0c0s2b0

  redis:
    image: artifactory.algol60.net/docker.io/library/redis:5.0-alpine3.12
    hostname: hms-redfish-redis
    networks:
      - scsd
