version: '3.7'
#THIS environment sets up all of SCSD
#TODO
#  All dependencies -> HSM (vault, hm-collector, kafka), RTS (redfish sims) are all setup and active.
#  The SCSD binary is active.
#  No ports are exposed to the local system.
#  This will be used for integration testing.
networks:
  scsd:

services:
  integration-tests:
    build:
      context: test/integration/
      dockerfile: Dockerfile
    environment:
      - SCSD=cray-scsd:25309
      #TODO
      #- HSM=cray-smd:27779
      - HSM=fake-smd:27779
      - X_S0_HOST=x0c0s480b0
      - X_S0_PORT=34800
      - X_S1_HOST=x0c0s481b0
      - X_S1_PORT=34801
      - X_S2_HOST=x0c0s482b0
      - X_S2_PORT=34802
      - X_S3_HOST=x0c0s483b0
      - X_S3_PORT=34803
      #TODO: s4?
      #TODO: s5?
      - X_S6_HOST=x0c0s486b0
      - X_S6_PORT=34806
      - X_S7_HOST=x0c0s487b0
      - X_S7_PORT=34807
    depends_on:
      - cray-scsd
      - x0c0s480b0
      - x0c0s481b0
      - x0c0s482b0
      - x0c0s483b0
      - x0c0s486b0
      - x0c0s487b0
    networks:
      - scsd

  # A collection of 8 fake Redfish endpoints

  # x_s0 (Mountain)
  x0c0s480b0:
    hostname: x0c0s480b0
    container_name: x0c0s480b0
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s480b0n0
      - BMCPORT=:34800
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s1 (Mountain)
  x0c0s481b0:
    hostname: x0c0s481b0
    container_name: x0c0s481b0
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s481b0n0
      - BMCPORT=:34801
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s2 (Mountain)
  x0c0s482b0:
    hostname: x0c0s482b0
    container_name: x0c0s482b0
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s482b0n0
      - BMCPORT=:34802
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s3 (Mountain)
  x0c0s483b0:
    hostname: x0c0s483b0
    container_name: x0c0s483b0
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s483b0n0
      - BMCPORT=:34803
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  #TODO: x_s4?
  #TODO: x_s5?

  # x_s6 (Mountain)
  x0c0s486b0:
    hostname: x0c0s486b0
    container_name: x0c0s486b0
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s486b0n0
      - BMCPORT=:34806
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  # x_s7 (Mountain)
  x0c0s487b0:
    hostname: x0c0s487b0
    container_name: x0c0s487b0
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-rfep
    environment:
      - XNAME=x0c0s487b0n0
      - BMCPORT=:34807
      - NACCTS=1
      - GOODACCT=1
      - VENDOR=cray
    networks:
      - scsd

  cray-scsd:
    build:
      context: .
      dockerfile: Dockerfile.test.integration
      args:
        IN_SCSD_TEST_K8S_AUTH_URL: ${SCSD_TEST_K8S_AUTH_URL}
        IN_SCSD_TEST_VAULT_PKI_URL: ${SCSD_TEST_VAULT_PKI_URL}
        IN_SCSD_TEST_VAULT_CA_URL: ${SCSD_TEST_VAULT_CA_URL}
        IN_CRAY_VAULT_JWT_FILE: ${CRAY_VAULT_JWT_FILE}
        IN_CRAY_VAULT_ROLE_FILE: ${CRAY_VAULT_ROLE_FILE}
    environment:
      #TODO
      #- SCSD_SMD_URL=http://cray-smd:27779/hsm/v2
      - SCSD_SMD_URL=http://fake-smd:27779/hsm/v1
      - SCSD_HTTP_LISTEN_PORT=25309
      - SCSD_LOCAL_MODE=true
      - SCSD_DEFAULT_HTTP=true
      - SCSD_LOG_LEVEL=TRACE
      - VAULT_ENABLE=0
      - IN_SCSD_TEST_K8S_AUTH_URL=:${SCSD_TEST_K8S_AUTH_URL}
      - IN_SCSD_TEST_VAULT_PKI_URL=:${SCSD_TEST_VAULT_PKI_URL}
      - IN_SCSD_TEST_VAULT_CA_URL=:${SCSD_TEST_VAULT_CA_URL}
      - IN_CRAY_VAULT_JWT_FILE=:${CRAY_VAULT_JWT_FILE}
      - IN_CRAY_VAULT_ROLE_FILE=:${CRAY_VAULT_ROLE_FILE}
    networks:
      - scsd
    depends_on:
      - fake-smd
      - fake-vault

  fake-smd:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-hsm
    hostname: fake-smd
    ports:
      - "27779:27779"
    environment:
      - PORT=:27779
    networks:
      - scsd

  fake-vault:
    build:
      context: test/integration
      dockerfile: Dockerfile.fake-vault
    hostname: fake-vault
    networks:
      - scsd
