# MIT License
#
# (C) Copyright [2020-2021] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Dockerfile for building HMS fake Redfish endpoints for testing.
# Author: mpkelly
# Date: 26-February 2020

# Base image contains everything needed for Go building, just build.
FROM artifactory.algol60.net/docker.io/library/golang:1.16-alpine AS builder

RUN go env -w GO111MODULE=auto

COPY fake-rfep.go ${GOPATH}/src/fake-rfep/

RUN set -ex && go build -v -i -o /usr/local/bin/fake-rfep fake-rfep

### Final Stage ###

FROM artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine:3.15
LABEL maintainer="Hewlett Packard Enterprise"
STOPSIGNAL SIGTERM

ENV PORT=27999
ENV GOODACCT=2

# Copy the final binary.

COPY --from=builder /usr/local/bin/fake-rfep /usr/local/bin

# Run the fake State Mgr daemon

CMD ["sh", "-c", "fake-rfep"]
